import 'package:hive/hive.dart';

part 'scrap_transaction.g.dart'; // generated by build_runner (hive_generator)

/// Every scrap handover is stored locally first (offline-first requirement),
/// then flagged `synced = true` once it reaches the backend.
@HiveType(typeId: 0)
class ScrapTransaction extends HiveObject {
  @HiveField(0)
  String id; // UUID, generated on-device so it works with no internet

  @HiveField(1)
  String materialType; // PCB, cable, battery, CRT, LCD, motor, plastic...

  @HiveField(2)
  double weightKg;

  @HiveField(3)
  double estimatedValue; // AI/price-list estimate at capture time

  @HiveField(4)
  String? recyclerId; // null until a recycler is matched/confirmed

  @HiveField(5)
  String? recyclerName;

  @HiveField(6)
  double? latitude;

  @HiveField(7)
  double? longitude;

  @HiveField(8)
  DateTime timestamp;

  @HiveField(9)
  String paymentStatus; // 'pending', 'paid'

  @HiveField(10)
  String? photoPath; // local file path to the captured scrap photo

  @HiveField(11)
  bool synced; // false = only exists locally, needs to sync to server

  ScrapTransaction({
    required this.id,
    required this.materialType,
    required this.weightKg,
    required this.estimatedValue,
    this.recyclerId,
    this.recyclerName,
    this.latitude,
    this.longitude,
    required this.timestamp,
    this.paymentStatus = 'pending',
    this.photoPath,
    this.synced = false,
  });
}
